image: ros:melodic-robot

variables:
  ROS_PACKAGES_TO_INSTALL: ""

cache:
  paths:
    - ccache/

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

catkin_make:
  stage: build
  script:
    - catkin_make

catkin_make roslint:
  stage: test
  script:
    - catkin_make roslint

catkin_make run_tests:
  stage: test
  script:
    - catkin_make run_tests

catkin lint:
  stage: test
  image: ros:melodic-robot
  before_script:
    - apt update >/dev/null 2>&1
    - apt install -y python-catkin-lint >/dev/null 2>&1
  script:
    - catkin_lint --strict .

